[package]
authors = ["Jan <jankaul@mailbox.org>"]
edition = "2021"
name = "dashbook-markdown"
version = "0.2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = "0.9.2"
wit-bindgen = "0.36"
